### ISSUE TITLE
Mailgun redirects to email.domain instead of my link

### ISSUE THREAD

**Issue by CrestNiraj12** [CrestNiraj12/portfolio-website#31]
When sending mail with nodemailer, if I attach a link in the mail, and when the client receives the mail, a fully different link opens in the browser if I click on the link. For example, if I send https://nirajshrestha.live/{some token} and send it to myself, and when I click on the link the link automatically opens https://email.nirajshrestha.live/{random-hash-keys}.

This issue only happens in production due to mailgun and works completely fine in development.

**Comment by CrestNiraj12** [comment]
Solved

**Comment by ChahinSouilmi** [comment]
how did you fix it ?
